name = "rss-pipeline-api"
main = "src/index.ts"
compatibility_date = "2026-06-27"

[[queues.producers]]
queue = "article-extraction-queue"

[vars]
SUPABASE_URL = ""
SUPABASE_SERVICE_KEY = ""
FEISHU_APP_ID = ""
FEISHU_APP_SECRET = ""
FEISHU_VERIFICATION_TOKEN = ""
FEISHU_ENCRYPT_KEY = ""